export type WireframeDomain =
  | "auth"
  | "home"
  | "buyer"
  | "seller"
  | "my"

export type WireframeScreen = {
  id: string
  name: string
  domain: WireframeDomain
  path: string
  priority: "P0" | "P1" | "P2"
  variant?: boolean
}

export const WIREFRAME_SCREENS: WireframeScreen[] = [
  { id: "SPL", name: "스플래시", domain: "auth", path: "/splash", priority: "P0" },
  { id: "LGN", name: "로그인", domain: "auth", path: "/auth/login", priority: "P0" },
  { id: "SGN", name: "회원가입 (3단계)", domain: "auth", path: "/auth/signup", priority: "P0" },
  {
    id: "ACCT",
    name: "환급·정산 계좌 등록",
    domain: "auth",
    path: "/auth/bank-account",
    priority: "P0",
  },
  { id: "HOME", name: "홈", domain: "home", path: "/home", priority: "P0" },
  { id: "SRCH", name: "빈자리 검색", domain: "buyer", path: "/search", priority: "P0" },
  {
    id: "SRCH-E",
    name: "검색 결과 없음",
    domain: "buyer",
    path: "/search/empty",
    priority: "P0",
    variant: true,
  },
  {
    id: "ALRT",
    name: "자리 알림 대기등록 (팝업)",
    domain: "buyer",
    path: "/waitlist",
    priority: "P0",
  },
  { id: "DETL", name: "공구 상세", domain: "buyer", path: "/deals/[dealId]", priority: "P0" },
  {
    id: "DETL-C",
    name: "전 자리 마감",
    domain: "buyer",
    path: "/deals/[dealId]/closed",
    priority: "P0",
    variant: true,
  },
  {
    id: "APLY",
    name: "신청·배송정보 입력",
    domain: "buyer",
    path: "/deals/[dealId]/apply",
    priority: "P0",
  },
  {
    id: "CHKO",
    name: "입금 안내 (가상계좌)",
    domain: "buyer",
    path: "/deals/[dealId]/deposit",
    priority: "P0",
  },
  {
    id: "CHKO-X",
    name: "입금 기한 만료",
    domain: "buyer",
    path: "/deals/[dealId]/deposit/expired",
    priority: "P0",
    variant: true,
  },
  {
    id: "DONE",
    name: "신청 완료",
    domain: "buyer",
    path: "/deals/[dealId]/complete",
    priority: "P0",
  },
  {
    id: "MYJN",
    name: "내 참여 현황 (목록)",
    domain: "buyer",
    path: "/participations",
    priority: "P0",
  },
  {
    id: "MYJN-D",
    name: "내 참여 현황 (상세)",
    domain: "buyer",
    path: "/participations/[participantId]",
    priority: "P0",
    variant: true,
  },
  {
    id: "MYJN-A",
    name: "배송지 변경",
    domain: "buyer",
    path: "/participations/[participantId]",
    priority: "P0",
    variant: true,
  },
  {
    id: "MYJN-C",
    name: "배송 조회",
    domain: "buyer",
    path: "/participations/[participantId]",
    priority: "P0",
    variant: true,
  },
  {
    id: "RPTB",
    name: "공구 리포트 (참여자)",
    domain: "buyer",
    path: "/deals/[dealId]/report",
    priority: "P0",
  },
  {
    id: "RVEW",
    name: "후기·평점 작성 (팝업)",
    domain: "buyer",
    path: "/reviews/new",
    priority: "P1",
  },
  {
    id: "CLAM",
    name: "분쟁 신고 (팝업)",
    domain: "buyer",
    path: "/disputes/new",
    priority: "P1",
  },
  {
    id: "CRTE",
    name: "공구 개설 (4단계)",
    domain: "seller",
    path: "/seller/create/shipping",
    priority: "P0",
  },
  {
    id: "CRTE-D",
    name: "보증금 예치 (4단계)",
    domain: "seller",
    path: "/seller/create/deposit",
    priority: "P0",
    variant: true,
  },
  {
    id: "DASH",
    name: "총대 대시보드",
    domain: "seller",
    path: "/seller/deals/[dealId]",
    priority: "P0",
  },
  {
    id: "RPTG",
    name: "공구 리포트 (총대)",
    domain: "seller",
    path: "/seller/deals/[dealId]/report",
    priority: "P0",
  },
  {
    id: "QFIL",
    name: "공석 급구",
    domain: "seller",
    path: "/seller/deals/[dealId]/urgent-fill",
    priority: "P0",
  },
  {
    id: "SEAT",
    name: "공석 처리",
    domain: "seller",
    path: "/seller/deals/[dealId]/seats",
    priority: "P0",
  },
  {
    id: "RECR",
    name: "공구 홍보·마감 관리",
    domain: "seller",
    path: "/seller/deals/[dealId]/recruitment",
    priority: "P0",
  },
  {
    id: "FINL",
    name: "모집 마감·주문 명단 확정",
    domain: "seller",
    path: "/seller/deals/[dealId]/finalize",
    priority: "P0",
  },
  {
    id: "PACK",
    name: "포장 취합표",
    domain: "seller",
    path: "/seller/deals/[dealId]/packing",
    priority: "P0",
  },
  {
    id: "PURC",
    name: "1차 구매·영수증 인증",
    domain: "seller",
    path: "/seller/deals/[dealId]/purchase-proof",
    priority: "P0",
  },
  {
    id: "PURC-V",
    name: "수량 검증",
    domain: "seller",
    path: "/seller/deals/[dealId]/purchase/verify",
    priority: "P0",
  },
  {
    id: "PURC-F",
    name: "검증 실패·소명 요청",
    domain: "seller",
    path: "/seller/deals/[dealId]/purchase/failed",
    priority: "P0",
    variant: true,
  },
  {
    id: "OPEN",
    name: "개봉·배정",
    domain: "seller",
    path: "/seller/deals/[dealId]/opening",
    priority: "P0",
  },
  {
    id: "OPEN-S",
    name: "수량 부족·미배정",
    domain: "seller",
    path: "/seller/deals/[dealId]/opening/shortage",
    priority: "P0",
    variant: true,
  },
  {
    id: "DIST-M",
    name: "수동 배분 조정",
    domain: "seller",
    path: "/seller/deals/[dealId]/manual-distribution",
    priority: "P0",
    variant: true,
  },
  {
    id: "SHIP",
    name: "발송 관리",
    domain: "seller",
    path: "/seller/deals/[dealId]/shipping",
    priority: "P0",
  },
  {
    id: "SHIP-C",
    name: "매칭 확인 필요",
    domain: "seller",
    path: "/seller/deals/[dealId]/shipping/confirm",
    priority: "P0",
    variant: true,
  },
  {
    id: "STLM",
    name: "정산",
    domain: "seller",
    path: "/seller/deals/[dealId]/settlement",
    priority: "P0",
  },
  { id: "MYPG", name: "마이페이지 홈", domain: "my", path: "/my", priority: "P0" },
  { id: "MACC", name: "계좌 관리", domain: "my", path: "/my/account", priority: "P1" },
  {
    id: "MID0",
    name: "내 공구 관리 (총대용)",
    domain: "my",
    path: "/my/hosted",
    priority: "P1",
  },
  {
    id: "MIP0",
    name: "내 참여 관리 (참여자용)",
    domain: "my",
    path: "/my/participations",
    priority: "P1",
  },
  {
    id: "MJPT",
    name: "내 참여 관리 (참여자)",
    domain: "my",
    path: "/my/participations",
    priority: "P1",
    variant: true,
  },
  {
    id: "MBTL",
    name: "정산·환불 내역",
    domain: "my",
    path: "/my/settlements",
    priority: "P1",
  },
  {
    id: "MTR0",
    name: "신뢰도·후기 관리",
    domain: "my",
    path: "/my/trust-reviews",
    priority: "P2",
  },
  { id: "MINF", name: "내 정보 관리", domain: "my", path: "/my/profile", priority: "P1" },
  { id: "MALM", name: "알림 설정", domain: "my", path: "/my/notifications", priority: "P1" },
  {
    id: "MCS",
    name: "고객센터·분쟁",
    domain: "my",
    path: "/my/support",
    priority: "P1",
  },
]

export const WIREFRAME_DOMAIN_LABELS: Record<WireframeDomain, string> = {
  auth: "공통·인증",
  home: "홈",
  buyer: "참여자",
  seller: "총대",
  my: "마이페이지",
}

export const getScreenById = (id: string) =>
  WIREFRAME_SCREENS.find((screen) => screen.id === id)
