import type { Dictionary } from "@i18n/types"

export const buildParticipationsListLabels = (
  t: Dictionary["account"]["participations"]
) => ({
  tabActive: t.tabActive,
  tabCompleted: t.tabCompleted,
  tabCancelled: t.tabCancelled,
  empty: t.empty,
  emptyActive: t.emptyActive,
  emptyActiveCta: t.emptyActiveCta,
  emptyCompleted: t.emptyCompleted,
  emptyCancelled: t.emptyCancelled,
  autoDeliveryConfirmHint: t.autoDeliveryConfirmHint,
  deliveryConfirmNeededAlert: t.deliveryConfirmNeededAlert,
  quantity: t.quantity,
  viewDeal: t.viewDeal,
  viewDetail: t.viewDetail,
  memberLabel: t.memberLabel,
  memberFallback: t.memberFallback,
  statusCancelled: t.statusCancelled,
  statusRefunded: t.statusRefunded,
  tracking: t.tracking,
  confirmDelivery: t.confirmDelivery,
  confirmingDelivery: t.confirmingDelivery,
  deliveryConfirmed: t.deliveryConfirmed,
  confirmDeliveryError: t.confirmDeliveryError,
  confirmPurchase: t.confirmPurchase,
  confirmPurchaseTitle: t.confirmPurchaseTitle,
  confirmPurchaseMessage: t.confirmPurchaseMessage,
  confirmPurchaseConfirm: t.confirmPurchaseConfirm,
  confirmPurchaseCancel: t.confirmPurchaseCancel,
  cancelParticipation: t.cancelParticipation,
  cancelParticipationTitle: t.cancelParticipationTitle,
  cancelParticipationMessage: t.cancelParticipationMessage,
  cancelParticipationConfirm: t.cancelParticipationConfirm,
  cancelParticipationDismiss: t.cancelParticipationDismiss,
  cancelParticipationSuccess: t.cancelParticipationSuccess,
  cancelParticipationError: t.cancelParticipationError,
  progressStages: t.progressStages,
})
